version: '3.9'

services:

  db:
    image: postgres
    container_name: postgres_db
    restart: on-failure
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "django_user"
      POSTGRES_PASSWORD: "django_password"
      POSTGRES_DB: "django_db"
      TZ: "Europe/Moscow"
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 1s

  web:
    build: ./django_app
    container_name: django
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres:

